"""_proto.py – _CodeGeneratorBase

Mixin 間で共有されるインスタンス変数とメソッドシグネチャを宣言する基底クラス。
各 Mixin がこのクラスを継承することで、Pylance が cross-Mixin の self.xxx 参照をエラーなく解決できるようになる。
実際の実装は MRO 上の CodeGenerator および各 Mixin が提供する。
"""
from __future__ import annotations
from typing import Any

class _CodeGeneratorBase:
    """型ヒント用インターフェース宣言。実装は各 Mixin と CodeGenerator が提供する。"""

    # ------------------------------------------------------------------
    # インスタンス変数 (CodeGenerator.__init__ で初期化される)
    # ------------------------------------------------------------------
    code:                        list[str]
    indent_level:                int
    struct_defs:                 dict[str, Any]
    function_defs:               list[Any]
    structs:                     list[Any]
    array_sizes:                 dict[str, Any]
    loop_counter:                int
    generic_instantiations:      dict[Any, Any]
    program_functions:           dict[str, Any]
    env:                         list[dict[str, Any]]
    temp_string_counter:         int
    const_table:                 dict[str, Any]
    lambda_counter:              int
    pending_lambdas:             list[Any]
    pending_async_lambda_blocks: list[Any]
    async_lambda_factories:      dict[str, str]
    sm_mode:                     bool
    sm_vars:                     set[str]
    sm_await_handles:            dict[int, str]
    capture_map:                 dict[str, str]
    closure_env_types:           dict[str, str]
    result_type_registry:        set[tuple[str, str, str]]
    current_return_type:         str | None
    enums:                       dict[str, Any]
    ident_renames:               dict[str, str]
    local_string_vars:           list[str]
    vec_var_types:               dict[str, str]

    # ------------------------------------------------------------------
    # 出力系 (__init__.py 実装)
    # ------------------------------------------------------------------
    def _emit(self, line: str = "") -> None: ...
    def _emit_raw(self, text: str) -> None: ...
    def _emit_pending_lambdas_at(self, insert_pos: int) -> None: ...

    # ------------------------------------------------------------------
    # 型変換 (_type.py 実装)
    # ------------------------------------------------------------------
    def _type_to_c(self, type_node: Any) -> str: ...
    def _type_to_c_base(self, type_name: str) -> str: ...
    def _type_to_fmt_spec(self, arg_expr: Any) -> str: ...
    def _emit_result_typedefs(self) -> None: ...

    # ------------------------------------------------------------------
    # 式・文生成 (_expr.py / _stmt.py 実装)
    # ------------------------------------------------------------------
    def _generate_expr(self, expr: Any) -> str: ...
    def _generate_expr_with_temps(self, expr: Any, temp_string_mapping: dict) -> str: ...
    def _generate_statement(self, stmt: Any) -> None: ...
    def _generate_function_call(self, expr: Any) -> str: ...
    def _generate_print_call(self, expr: Any) -> str: ...
    def _generate_struct_init(self, expr: Any) -> str: ...
    def _generate_match_expr(self, expr: Any) -> str: ...
    def _generate_method_call(self, expr: Any) -> str: ...
    def _match_pattern_to_c(self, mv: str, pattern: Any, scrutinee_is_string: bool) -> Any: ...
    def _pattern_binding_types(self, pattern: Any) -> dict[str, str]: ...
    def _infer_match_result_c_type(self, arms: Any) -> str: ...
    def _generate_conditional_block(self, stmt: Any) -> None: ...
    def _generate_let(self, stmt: Any) -> None: ...
    def _generate_return(self, stmt: Any) -> None: ...
    def _generate_if(self, stmt: Any) -> None: ...
    def _generate_if_inline(self, stmt: Any) -> None: ...
    def _generate_while(self, stmt: Any) -> None: ...
    def _generate_for(self, stmt: Any) -> None: ...
    def _generate_array_element(self, array_expr: Any, index: Any) -> str: ...

    # ------------------------------------------------------------------
    # 関数・メソッド生成 (__init__.py 実装)
    # ------------------------------------------------------------------
    def _generate_function(self, func: Any) -> None: ...
    def _generate_method(self, struct_name: str, method: Any) -> None: ...

    # ------------------------------------------------------------------
    # 構造体 (_struct.py 実装)
    # ------------------------------------------------------------------
    def _generate_struct(self, struct: Any) -> None: ...
    def _generate_enum(self, enum_decl: Any) -> None: ...
    def _generate_enum_variant_expr(self, expr: Any) -> str: ...
    def _infer_struct_name(self, method_name: str) -> str: ...

    # ------------------------------------------------------------------
    # ラムダ (_lambda.py 実装)
    # ------------------------------------------------------------------
    def _body_has_await(self, body: Any) -> bool: ...
    def _collect_captures(self, node: Any, param_names: set) -> dict[str, str]: ...
    def _generate_lambda(self, expr: Any) -> str: ...
    def _generate_lambda_inline(self, expr: Any, var_name: str) -> Any: ...
    def _generate_async_lambda(self, expr: Any, lam_name: str) -> str: ...

    # ------------------------------------------------------------------
    # 非同期 SM (_async.py 実装)
    # ------------------------------------------------------------------
    def _sm_let_c_type(self, stmt: Any) -> str: ...
    def _split_by_await(self, stmts: Any) -> list[Any]: ...
    def _generate_async_state_machine(self, func: Any) -> None: ...
    def _emit_await_setup(self, await_stmt: Any, next_state: int, await_index: int = 0) -> None: ...
    def _emit_await_resume(self, await_stmt: Any, await_index: int = 0) -> None: ...
    def _generate_sm_stmt(self, stmt: Any, func: Any, has_return_val: bool) -> None: ...
    def _emit_task_complete(self, func: Any, has_return_val: bool) -> None: ...
    def _emit_task_factory(self, func: Any, sm_struct: str, move_next: str) -> None: ...
    def _emit_main_sm_entry(self, sm_struct: str, move_next: str) -> None: ...
    def _emit_task_runtime(self) -> None: ...

    # ------------------------------------------------------------------
    # ジェネリクス (_generic.py 実装)
    # ------------------------------------------------------------------
    def _register_generic_instantiation(self, func_name: str, type_args: Any) -> None: ...
    def _substitute_function(self, func: Any, subst: dict[str, Any], type_args_tuple: Any) -> Any: ...
    def _substitute_type_node(self, type_node: Any, subst: dict[str, Any]) -> Any: ...
    def _get_instantiated_func_name(self, func_name: str, type_args_tuple: Any) -> str: ...
    def _infer_generic_type_args(self, func: Any, arg_exprs: Any) -> list[Any]: ...
    def _infer_expr_type(self, expr: Any) -> str: ...
    def _scan_generic_calls(self, block: Any) -> None: ...
    def _scan_statement_for_generic_calls(self, stmt: Any) -> None: ...
    def _scan_expr_for_generic_calls(self, expr: Any) -> None: ...

    # ------------------------------------------------------------------
    # ユーティリティ (_util.py 実装) ※ static method
    # ------------------------------------------------------------------
    @staticmethod
    def _c_escape(s: str) -> str: ...
    @staticmethod
    def _strip_outer_parens(s: str) -> str: ...
    @staticmethod
    def _to_pascal(name: str) -> str: ...

    # ------------------------------------------------------------------
    # ヘッダ出力 (_header.py 実装)
    # ------------------------------------------------------------------
    def _emit_includes(self) -> None: ...
    def _emit_builtin_types(self) -> None: ...
    def _collect_vec_elem_types(self, program: Any) -> set[str]: ...
    def _emit_vec_helpers(self, elem_types: set[str]) -> None: ...
    def _emit_builtin_functions(self) -> None: ...
    def _emit_header(self) -> None: ...

    # ------------------------------------------------------------------
    # 定数 (_const.py 実装)
    # ------------------------------------------------------------------
    def _generate_const(self, const_decl: Any) -> None: ...
    def _eval_const_expr(self, expr: Any) -> Any: ...
